### ISSUE TITLE
Notification body does not escape '%'

### ISSUE THREAD

**Issue by wberger** [beaconinside/BeaconService#2]
Our campaign texts contain '%' characters, e.g. "20 % Rabatt". When scheduling local notifications, the '%' has to be escaped in order to be displayed correctly, as described in Apple's documentation:

https://developer.apple.com/reference/uikit/uilocalnotification/1616646-alertbody

> Assign a string or, preferably, a localized-string key (using NSLocalizedString) as the value of the message. If the value of this property is non-nil, an alert is displayed. The default value is nil (no alert). Printf style escape characters are stripped from the string prior to display; to include a percent symbol (%) in the message, use two percent symbols (%%).

Currently, BeaconService does not escape the '%' when using the campaign the for the notification body and the displayed text is "20 Rabatt", which is not the expected behaviour.

Would you please provide a fix for this?

**Comment by rabschi** [comment]
Thanks for reporting this issue. This issue will be fixed in the 2.8.0 release, scheduled for Wednesday in the new repository: https://github.com/beaconinside/ios-sdk
