### ISSUE TITLE
Customize alert button texts?

### ISSUE THREAD

**Issue by wberger** [beaconinside/BeaconService#3]
Hi,

By default, the in-app alert for beacon messages shows "Cancel" and "OK". I would like to change that to "Schließen" and "Anzeigen". Is there a way to do this?

I was able to change "Cancel" to "Abbrechen" by adding a localization strings file, but cannot to anything more.

Preferably I would like to be to set strings for ok/cancel via some options.

**Comment by rabschi** [comment]
We are working on a custom notification handler to keep the app publisher in full control. I'll comment on this thread when it's available.

**Comment by rabschi** [comment]
For iOS and Android since v2.10 we now provide solutions for custom campaign meta data that can be visualised in various ways, including notifications with images and custom action buttons.
